README.md, README_zh.md
Signed-off-by: bingshen.wbs <bingshen.wbs@alibaba-inc.com>
=> fix markdown lint issues

Dockerfile, README.md, README_zh.md
Signed-off-by: bingshen.wbs <bingshen.wbs@alibaba-inc.com>
=> fix gh-action using mainland mirror & fix skoop install command

pkg/skoop/model/netnode.go, pkg/skoop/model/path.go, pkg/skoop/nodemanager/net_node_manager.go, pkg/skoop/plugin/calico.go, pkg/skoop/plugin/flannel.go, pkg/skoop/plugin/simple.go
And move GenericNetNode to package "plugin" to prevent import cycle.
=> fix panic when no service endpoint and exited when non pod/node address as source

pkg/exporter/probe/procsoftnet/procsoftnet.go
Fix probe `softnet` by changing the file detection of `/proc/net/softnet` to `/proc/net/softnet_stat`
=> fix probe "softnet"

pkg/skoop/collector/manager/config.go, pkg/skoop/collector/manager/manager.go
Add option --preserve-collector-pod for SimplePodCollector to make collector diagnosis easier.
=> Add option to preserve collector pod

pkg/skoop/service/service.go
=> fix panic when check external traffic in networkpolicy

deploy/resource/kubeskoop-exporter-dashboard.json, pkg/exporter/cmd/metricserver.go
=> fix metrics label override by prometheus operator default scrape rule

pkg/exporter/cmd/root.go, pkg/exporter/nettop/cache.go, pkg/exporter/nettop/nodemeta.go, pkg/exporter/nettop/pod.go, pkg/exporter/probe/procnetdev/procnetdev.go, pkg/exporter/probe/procsock/procsock.go, pkg/exporter/probe/proctcpsummary/proctcp.go
Signed-off-by: xiayu.lyt <xiayu.lyt@alibaba-inc.com>
=> feat(exporter): add sidecar mode 

go.mod, pkg/exporter/cmd/server.go, pkg/exporter/probe/event.go, pkg/exporter/probe/flow/flow.go, pkg/exporter/probe/metrics.go, pkg/exporter/probe/nlconntrack/conntrackevents.go, pkg/exporter/probe/nlconntrack/conntrackmetrics.go, pkg/exporter/probe/nlqdisc/nlqdiscstats.go, pkg/exporter/probe/procfd/procfd.go, pkg/exporter/probe/procio/procio.go, pkg/exporter/probe/procipvs/ipvsservicestats.go, pkg/exporter/probe/procnetdev/procnetdev.go, pkg/exporter/probe/procnetstat/procnetstat.go, pkg/exporter/probe/procsnmp/procsnmp.go, pkg/exporter/probe/procsock/procsock.go, pkg/exporter/probe/procsoftnet/procsoftnet.go, pkg/exporter/probe/proctcpsummary/proctcp.go, pkg/exporter/probe/tracebiolatency/tracebiolatency.go, pkg/exporter/probe/tracekernel/tracekernel.go, pkg/exporter/probe/tracenetiftxlatency/tracenetiftxlatency.go, pkg/exporter/probe/tracenetsoftirq/tracenetsoftirq.go, pkg/exporter/probe/tracepacketloss/packetloss.go, pkg/exporter/probe/tracesocketlatency/socketlatency.go, pkg/exporter/probe/tracetcpreset/tracetcpreset.go, pkg/exporter/probe/tracevirtcmdlat/tracevirtcmdlat.go, pkg/exporter/probe/util.go, pkg/exporter/probe/util_test.go
Signed-off-by: xiayu.lyt <xiayu.lyt@alibaba-inc.com>
=> feat(exporter): custom args

webui/internal/service/config/config.go, webui/src/components/WebFrameCard/index.module.css
fix https://github.com/alibaba/kubeskoop/issues/151
=> feat: display pod selection on monitoring dashboard

deploy/resource/kubeskoop-exporter-dashboard.json, deploy/skoopbundle.yaml, pkg/exporter/cmd/eventserver.go, pkg/exporter/probe/procio/procio.go, pkg/exporter/probe/tracekernel/tracekernel.go, pkg/exporter/probe/tracenetiftxlatency/tracenetiftxlatency.go, pkg/exporter/probe/tracenetsoftirq/tracenetsoftirq.go, pkg/exporter/probe/tracepacketloss/packetloss.go, pkg/exporter/probe/tracesocketlatency/socketlatency.go, pkg/exporter/probe/tracevirtcmdlat/tracevirtcmdlat.go
=> format metric names & dashboard use new metrics

pkg/skoop/plugin/calico.go
=> feat: support specific calico host mtu

webui/src/pages/capture/components/captureForm/index.module.css, webui/src/pages/capture/components/captureForm/index.tsx, webui/src/pages/capture/components/captureForm/selectorDialog.tsx, webui/src/pages/pingmesh/pingForm/index.module.css, webui/src/pages/pingmesh/pingForm/selectorDialog.tsx
=> fix(webui): enhance pod & node selection

pkg/exporter/nettop/cri.go
=> feat(exporter): support cri-dockerd

pkg/exporter/task-agent/agent.go
=> fix(exporter): fix agent reconnect

pkg/controller/service/diagnose.go, webui/src/pages/capture/components/captureResult/index.tsx, webui/src/pages/capture/index.tsx, webui/src/services/capture.ts
sort connectivity diagnosis & packet capturing histories in descending order
=> feature(webui): sort diagnosis & packet capturing histories

pkg/exporter/probe/tracekernel/tracekernel.go
Remove `kernellatency`  from event.probes in config.yml will stop the event probe, and the perfReader should be close at the same time.
=> close perfReader if stop event probe

.github/workflows/build.yml, Dockerfile, Makefile, deploy/helm/README.md, deploy/helm/values.yaml, deploy/resource/kubeskoop-exporter-dashboard.json, deploy/skoopbundle.yaml, deploy/vagrant-exporter/deploy/skoop-deploy.yaml, pkg/skoop/collector/manager/config.go, test/skoop/e2e/e2e_test.go
=> feat: split agent & controller image && reduce image size

deploy/resource/kubeskoop-exporter-dashboard.json, deploy/skoopbundle.yaml
=> bugfix: fix default deploy configuration

pkg/controller/diagnose/diagnose.go, pkg/skoop/network/aliyun/assertion.go, pkg/skoop/service/service.go
* fix cluster ip masq
* fix security group assertions
* add extra args in controller configmap
=> Fix flannel plugin pod -> svc diagnose 

pkg/controller/cmd/server.go, pkg/controller/graph/graph.go, webui/package.json, webui/src/pages/monitoring/flow/components/FlowGraph/index.tsx, webui/src/pages/monitoring/flow/index.tsx, webui/yarn.lock
1. filter out metrics values equal to 0
2. group external endpoints by private cidrs
3. display default time range
=> feat(flow): enhance flow ui

pkg/exporter/probe/tracekernel/tracekernel.go
t1: event prober start and failed load bpf, leave the refcnt == 1 
t2: metric prober start; refcnt == 2
start perf reader failed and call stop
deadlock on stop reentrant lock
=> bugfix: fix deadlock on prober start

pkg/exporter/nettop/cache.go, pkg/exporter/probe/nlconntrack/conntrackevents.go, pkg/exporter/probe/nlqdisc/nlqdiscstats.go
see https://github.com/alibaba/kubeskoop/issues/285
=> fix: close qdisc fd

deploy/skoopbundle.yaml
when use 'Connectivity Diagnosis', lack of authority
=> fix lack of authority

deploy/resource/kubeskoop-exporter-nodes-dashboard.json
=> add erdma metrics in dashboard
