.github/workflows/check.yml
pkg/exporter/bpfutil/format.go
pkg/exporter/cmd/eventserver.go
pkg/exporter/nettop/cri.go
pkg/exporter/nettop/netns_test.go
pkg/exporter/probe/metric.go
pkg/exporter/probe/procio/procio.go
pkg/exporter/probe/procnetdev/procnetdev.go
pkg/exporter/probe/procnetstat/procnetstat.go
pkg/exporter/probe/procsnmp/procsnmp.go
pkg/exporter/probe/procsock/procsock.go
pkg/exporter/probe/procsoftnet/procsoftnet.go
pkg/exporter/probe/tracekernel/tracekernel.go
pkg/exporter/probe/tracenetiftxlatency/tracenetiftxlatency.go
pkg/exporter/probe/tracenetsoftirq/tracenetsoftirq.go
pkg/exporter/probe/tracesocketlatency/socketlatency.go
pkg/exporter/probe/tracevirtcmdlat/tracevirtcmdlat.go
pkg/skoop/assertions/netstack.go
pkg/skoop/cmd/app.go
pkg/skoop/model/netnode.go
pkg/skoop/netstack/iptables.go
pkg/skoop/netstack/iptables_test.go
pkg/skoop/network/aliyun/infrashim.go
pkg/skoop/network/aliyun/network.go
pkg/skoop/plugin/calico.go
pkg/skoop/plugin/flannel.go
pkg/skoop/ui/web.go

upgrade `golangci-lint` to try to resolve failed lint workflow problem.

upgrade golangci-lint to v1.52.2

---

deploy/skoopbundle.yaml
pkg/exporter/cmd/diag.go
pkg/exporter/cmd/diag_metric.go
pkg/exporter/cmd/list.go
pkg/exporter/cmd/list_entity.go
pkg/exporter/cmd/list_event.go
pkg/exporter/cmd/list_metric.go
pkg/exporter/cmd/list_probe.go
pkg/exporter/cmd/server.go
pkg/exporter/probe/metric.go
pkg/exporter/probe/procfd/procfd.go

1. Add procfd probe, default not enabled.
2. Update bundle file.
3. Optimized the usage of command line and now it is possible to select JSON output format in the list command, as well as view event probes.

add procfd probe for socketmemleaks and update bundle file

---

pkg/exporter/cmd/list_entity.go

if we run `inspector list entity`  in a env without cri, there is no error showed if we do not add `-d` option, so I improve the behavour, now there is a message if an error like `sync nettop failed:rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService` occurred.

set inspector list entity error verbose

---

pkg/skoop/cmd/app.go
pkg/skoop/ui/html/index.html
pkg/skoop/ui/json.go
pkg/skoop/ui/web.go
test/skoop/e2e/framework/framework.go

fixes #61 
NetworkPolicy problems are considered as cluster-wide suspicions. But they're not be displayed in json format or Web UI.
This adds cluster-wide info to them.

add global suspicion to json format and web ui

---

README.md
README_zh.md

Provide `docker run` command with --http-address.
fixes #81

doc: fix docker run command with --http-address

---

pkg/skoop/netstack/link.go
pkg/skoop/netstack/link_test.go
pkg/skoop/plugin/calico.go
pkg/skoop/plugin/flannel.go

host interface detection for flannel & calico plugin

feat(diagnosis): add host interface detection 

---

bpf/netiftxlatency.c

Maybe this should be update not delete, the insp_txs map did not store any data before.

fix: insp_txs did not store

---

pkg/exporter/probe/flow/flow.go
pkg/exporter/probe/flow/flow_test.go

example
```
metrics:
probes:
- name: flow
args:
interface: eth*
```
probe will watch network interface change, and setup tc filter on every newly create nic whose name start with eth0 to enable flow collecting

support dynamic interface flow collector

---

pkg/exporter/probe/metrics.go

This pull request fixes the incorrect label of  `kubeskoop_flow_*` metrics.

fix(exporter): fix label out of order in mergeLabels

---

pkg/exporter/nettop/cache.go

to avoid too many logs in debug mode

change cgroup pids debug log to warning when no pids found

---

pkg/controller/diagnose/diagnose.go

In calico network cluster, `skoop` diagnose command need `calico-host-interface` args, which controller
don't support.
This PR is to support diagnose custom args.

support diagnose custom args

---

deploy/skoopbundle.yaml
pkg/skoop/assertions/netstack.go
pkg/skoop/plugin/calico.go

Add access to calico ippools in skoopbundle & use calico CR

---

pkg/exporter/probe/tracenetiftxlatency/tracenetiftxlatency.go

netiftxlat probe won't be loaded correcotly, errors like:
```text
INFO[0230] reload config, old config: null, new config: [{"name":"netiftxlat","args":null}]
INFO[0230] create metrics probe netiftxlat with args null
INFO[0230] start metrics probe netiftxlat
2024/02/14 12:08:05 INFO btf file loaded file=/sys/kernel/btf/vmlinux
ERRO[0232] netiftxlat failed load and attach bpf, err: loading objects: tracenetif.bpfObjects is not a pointer to struct
ERRO[0232] failed start probe netiftxlat, err: netiftxlat failed load bpf: loading objects: tracenetif.bpfObjects is not a pointer to struct
```

fix: fail to load probe netiftxlat

---

Dockerfile

Specify `3.19` alpine version in `Dockerfile` to improve build consistency.
And package `iptables-legacy` does not exist in base image version < `3.19`.

chore(build): specify 3.19 as alpine version

---

pkg/controller/service/pingmesh.go
webui/src/pages/pingmesh/pingForm/index.module.css
webui/src/pages/pingmesh/pingForm/index.tsx
webui/src/pages/pingmesh/pingForm/selectorDialog.tsx
webui/src/pages/pingmesh/pingGraph/index.tsx
webui/src/services/pingmesh.ts

* split source & destination on latency detect
* support ping ip target

support source&destination ping

---

deploy/net-exporter-config.yaml

metrics probe packetloss doesn't support `enableStack` args (event probe packetloss does), so remove it in example config file

remove packetloss metrics probe args in net-exporter-config.yaml

---

cmd/exporter/init.go
go.mod
go.sum
pkg/exporter/probe/rdma/erdma.go
pkg/exporter/probe/rdma/mellanox.go
pkg/exporter/probe/rdma/rdma.go

support rdma metrics:
metrics examples:
```
kubeskoop_rdma_erdma_verbs_dereg_mr_cnt{device="erdma_0",k8s_namespace="",k8s_node="cn-shanghai.10.0.4.82",k8s_pod="",port="1",type="erdma"} 2
kubeskoop_rdma_pd{device="erdma_0",k8s_namespace="",k8s_node="cn-shanghai.10.0.0.1",k8s_pod="",type="erdma"} 1
```
relate to #209

feat: support rdma resource metrics

---

pkg/exporter/cmd/config.go
pkg/exporter/cmd/server.go
pkg/exporter/nettop/cache.go
pkg/exporter/probe/legacy.go
pkg/exporter/probe/legacy_test.go

feat(metrics): add additional labels to metrics

---

pkg/exporter/cmd/eventserver.go
pkg/exporter/cmd/metricserver.go
pkg/exporter/cmd/server.go
pkg/exporter/nettop/cache.go

1. when closing probes, skip those probes in non running state
2. exit when receive sigint/sighup signals

bugfix: probe state

---

pkg/exporter/probe/legacy.go
pkg/exporter/probe/tracekernel/tracekernel.go
pkg/exporter/probe/tracenetiftxlatency/tracenetiftxlatency.go
pkg/exporter/probe/tracesocketlatency/socketlatency.go
pkg/exporter/probe/tracetcpreset/tracetcpreset.go

From now on, all metrics whose name start with 'inspect_' are not supported. 
The new metrics only have three labels (k8s_namespace, k8s_pod and k8s_node)

deprecate legacy metrics labels

---

pkg/skoop/netstack/link.go
pkg/skoop/netstack/link_test.go

**Solution:**
- Updated 'LookupDefaultIfaceName' to support additional naming conventions such as 'ens[0-9]+.*' and 'eth[0-9]+'.
**Related Issue:**
Fixes the error: 'cannot lookup default host interface, please manually specify it via --calico-host-interface'.
#322 
**Test plan:**
- Tested with interfaces named 'ens162', 'ens192', 'eth0', and 'lo'.
"

Fix: Enhance default interface detection logic
